apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.0.0
    chart: consul
    helm:
      values: |
        global:
          name: consul
          datacenter: dc1
          image: hashicorp/consul:1.14.4
        server:
          replicas: 3  # Optimisé pour vos 4 workers
          bootstrapExpect: 3
          disruptionBudget:
            enabled: true
            maxUnavailable: 0
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: consul
                    component: server
                topologyKey: kubernetes.io/hostname
  destination:
    server: https://kubernetes.default.svc
    namespace: consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m