apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: default
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.2.0
    helm:
      values: |
        global:
          name: consul
          datacenter: dc1
        
        server:
          replicas: 1
          bootstrapExpect: 1
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          storage:
            enabled: false
        
        client:
          enabled: true
          
        connectInject:
          enabled: false
          
        controller:
          enabled: false
          
        ui:
          enabled: true
          service:
            type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true