apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgatt
  namespace: rgatt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rgatt
  template:
    metadata:
      labels:
        app: rgatt
    spec:
      containers:
      - name: rgatt
        image: docker.io/sayk/rgatt:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rgatt
  namespace: rgatt
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rgatt