apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.0
    helm:
      releaseName: vault
      values: |
        global:
          enabled: true
          tlsDisable: false
        
        server:
          dev:
            enabled: false
          
          ha:
            enabled: true
            replicas: 3
            config: |
              ui = true
              
              listener "tcp" {
                tls_disable = 0
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              
              storage "consul" {
                path = "vault"
                address = "consul-server.consul.svc:8500"
                token = "vault-consul-token"  # À remplacer par un token réel
              }
              
              service_registration "kubernetes" {}
          
          affinity: |
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values: ["vault"]
                  topologyKey: "kubernetes.io/hostname"
          
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
        
        ui:
          enabled: true
          serviceType: "ClusterIP"
        
        injector:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true