services:
  halyard:
    image: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
    container_name: halyard
    ports:
      - "8084:8084"
      - "9000:9000"
    volumes:
      - ~/.hal:/home/spinnaker/.hal
      - ~/.kube:/home/spinnaker/.kube
      - ~/hal-init.sh:/home/spinnaker/hal-init.sh

    command: ["/home/spinnaker/hal-init.sh"]