apiVersion: v1
kind: Secret
metadata:
  name: cloud-key-secret
  namespace: chaos-mesh
type: Opaque
stringData:
  aws_access_key_id: <your-aws-access-key-id>
  aws_secret_access_key: <your-aws-secret-access-key>