apiVersion: v1
# The base domain for the cluster
baseDomain: <DOMAIN>
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  # Cluster name
  name: <CLUSTER-NAME>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
# Government/Military Restrictions
fips: false
# the secret you've pulled
pullSecret: '{"auths": ...}' 
# Your ssh public key privionned 
sshKey: 'ssh-ed25519 AAAA...'