{{- if .Values.simulation.podKill.enabled }}
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: chaos-{{ .Values.global.name_prefix }}-pod-kill
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  action: pod-kill
  mode: {{ .Values.simulation.podKill.mode }}
  value: '{{ .Values.simulation.podKill.value }}'
  selector:
    namespaces:
      - {{ .Values.simulation.podKill.targetNamespace }}
    labelSelectors:
      {{- range $key, $value := .Values.global.labelSelector }}
      {{ $key }}: '{{ $value }}'
      {{- end }}
{{- end }}
